// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metrics.proto

/*
Package metrics is a generated protocol buffer package.

It is generated from these files:
	metrics.proto

It has these top-level messages:
	MetricsModel
	MetricsResponse
*/
package metrics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricsModel struct {
	Metrics string `protobuf:"bytes,1,opt,name=metrics" json:"metrics,omitempty"`
}

func (m *MetricsModel) Reset()                    { *m = MetricsModel{} }
func (m *MetricsModel) String() string            { return proto.CompactTextString(m) }
func (*MetricsModel) ProtoMessage()               {}
func (*MetricsModel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MetricsModel) GetMetrics() string {
	if m != nil {
		return m.Metrics
	}
	return ""
}

type MetricsResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *MetricsResponse) Reset()                    { *m = MetricsResponse{} }
func (m *MetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*MetricsResponse) ProtoMessage()               {}
func (*MetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MetricsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*MetricsModel)(nil), "metrics.MetricsModel")
	proto.RegisterType((*MetricsResponse)(nil), "metrics.MetricsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Metrics service

type MetricsClient interface {
	Exchange(ctx context.Context, in *MetricsModel, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type metricsClient struct {
	cc *grpc.ClientConn
}

func NewMetricsClient(cc *grpc.ClientConn) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) Exchange(ctx context.Context, in *MetricsModel, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := grpc.Invoke(ctx, "/metrics.Metrics/Exchange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Metrics service

type MetricsServer interface {
	Exchange(context.Context, *MetricsModel) (*MetricsResponse, error)
}

func RegisterMetricsServer(s *grpc.Server, srv MetricsServer) {
	s.RegisterService(&_Metrics_serviceDesc, srv)
}

func _Metrics_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metrics.Metrics/Exchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Exchange(ctx, req.(*MetricsModel))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exchange",
			Handler:    _Metrics_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}

func init() { proto.RegisterFile("metrics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x29,
	0xca, 0x4c, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x34, 0xb8,
	0x78, 0x7c, 0x21, 0x4c, 0xdf, 0xfc, 0x94, 0xd4, 0x1c, 0x21, 0x09, 0x2e, 0x98, 0x94, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x5c, 0xa5, 0x26, 0x17, 0x3f, 0x54, 0x65, 0x50, 0x6a, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x29, 0x4c, 0x2d, 0x94,
	0x67, 0xe4, 0xc1, 0xc5, 0x0e, 0x55, 0x2a, 0x64, 0xcb, 0xc5, 0xe1, 0x5a, 0x91, 0x9c, 0x91, 0x98,
	0x97, 0x9e, 0x2a, 0x24, 0xaa, 0x07, 0x73, 0x04, 0xb2, 0x95, 0x52, 0x12, 0xe8, 0xc2, 0x30, 0xf3,
	0x95, 0x18, 0x92, 0xd8, 0xc0, 0xce, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x44, 0x0a, 0x96,
	0x5b, 0xbf, 0x00, 0x00, 0x00,
}
